api_key : 5904b3c4-7835-4b64-a741-480681944340

files_names : {
               entsoe : {
                        imports : Imports.csv,
                        DE_AT_LU : DE_AT_LU_Exports.csv,
                        DE_LU   : DE_LU_Exports.csv,
                        DK_1 : DK_1_Exports.csv,
                        SE_4 : SE_4_Exports.csv,
                        Day_Ahead_Prices  : Day_Ahead_Prices.csv,
                        Load_And_Forecast : Load_And_Forecast.csv,
                        Wind_Solar_Forecast : Wind_Solar_Forecast.csv,
                        },
                yahoo : {
                        TTF  : TTF=F.csv,
                        COAL : CFI2Z3.csv,
                        CO2  : CO2_prices.csv
                        }
              }
